import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Check, FileImage, Flag, Gavel, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

function errorText(error: { message?: string }) { return error.message || "Something went wrong."; }
function statusLabel(status: string) { return status === "result_submitted" ? "Awaiting confirmation" : status === "confirmed" ? "Confirmed" : status === "disputed" ? "Disputed" : "Scheduled"; }
function statusVariant(status: string) { return status === "confirmed" ? "default" as const : status === "disputed" ? "destructive" as const : "secondary" as const; }

export default function MatchManagement() {
  const leagues = trpc.league.overview.useQuery(undefined, { refetchOnWindowFocus: false });
  const [leagueId, setLeagueId] = useState<number | null>(null);
  const [corrections, setCorrections] = useState<Record<number, { home: string; away: string }>>({});
  useEffect(() => { if (leagueId === null && leagues.data?.[0]) setLeagueId(leagues.data[0].id); }, [leagueId, leagues.data]);
  const matches = trpc.matchAdmin.list.useQuery({ leagueId: leagueId ?? 0 }, { enabled: leagueId !== null, refetchOnWindowFocus: false });
  const utils = trpc.useUtils();
  const resolve = trpc.matchAdmin.resolve.useMutation({ onSuccess: async () => { toast.success("Match workflow updated."); await utils.matchAdmin.list.invalidate(); await utils.league.dashboard.invalidate(); }, onError: (error) => toast.error(errorText(error)) });
  const grouped = useMemo(() => { const rows = matches.data ?? []; return { submitted: rows.filter((row) => row.status === "result_submitted"), disputed: rows.filter((row) => row.status === "disputed"), confirmed: rows.filter((row) => row.status === "confirmed"), scheduled: rows.filter((row) => row.status === "scheduled") }; }, [matches.data]);
  const correction = (id: number) => corrections[id] ?? { home: "", away: "" };
  const updateCorrection = (id: number, key: "home" | "away", value: string) => setCorrections((current) => ({ ...current, [id]: { ...correction(id), [key]: value } }));
  const renderCard = (fixture: NonNullable<typeof matches.data>[number]) => { const values = correction(fixture.id); return <Card key={fixture.id} className="rounded-[22px] border-border/80 shadow-none"><CardHeader className="border-b border-border/70"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><CardTitle className="text-base">{fixture.homeTeam.name} vs {fixture.awayTeam.name}</CardTitle><CardDescription className="mt-1">Round {fixture.round} · {fixture.homePlayer?.name ?? "Home player not assigned"} vs {fixture.awayPlayer?.name ?? "Away player not assigned"}</CardDescription></div><Badge variant={statusVariant(fixture.status)} className="w-fit rounded-full">{statusLabel(fixture.status)}</Badge></div></CardHeader><CardContent className="grid gap-4 p-5">{fixture.result && <div className="flex flex-col gap-3 rounded-xl bg-muted/60 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Submitted score</p><p className="mt-1 text-2xl font-black">{fixture.result.homeScore} – {fixture.result.awayScore}</p><p className="text-xs text-muted-foreground">Submitted by {fixture.result.submittedBy === fixture.homePlayer?.userId ? fixture.homePlayer?.name : fixture.awayPlayer?.name}</p></div>{fixture.result.proofUrl ? <a href={fixture.result.proofUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline"><FileImage className="size-4" /> View proof</a> : <span className="text-xs text-muted-foreground">No proof attached</span>}</div>}{(fixture.status === "result_submitted" || fixture.status === "disputed") && fixture.result && <div className="grid gap-3"><Button disabled={resolve.isPending} onClick={() => resolve.mutate({ fixtureId: fixture.id, action: "approve" })} className="w-fit rounded-xl"><Check className="size-4" /> Approve submitted result</Button><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input type="number" min={0} max={99} placeholder="Correct home score" value={values.home} onChange={(event) => updateCorrection(fixture.id, "home", event.target.value)} /><Input type="number" min={0} max={99} placeholder="Correct away score" value={values.away} onChange={(event) => updateCorrection(fixture.id, "away", event.target.value)} /><Button disabled={resolve.isPending || values.home === "" || values.away === ""} variant="outline" onClick={() => resolve.mutate({ fixtureId: fixture.id, action: "correct", homeScore: Number(values.home), awayScore: Number(values.away) })} className="rounded-xl"><Gavel className="size-4" /> Correct</Button></div><Button disabled={resolve.isPending} variant="ghost" onClick={() => resolve.mutate({ fixtureId: fixture.id, action: "cancel" })} className="w-fit rounded-xl text-destructive hover:bg-destructive/10 hover:text-destructive"><X className="size-4" /> Cancel submission</Button></div>}</CardContent></Card>; };
  return <div className="mx-auto max-w-[1280px] px-4 py-6 sm:px-8 sm:py-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-primary">Match management</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Keep every result accountable.</h1><p className="mt-2 text-sm text-muted-foreground">Review submissions, resolve disputes, and protect the official league table.</p></div>{leagues.data?.length ? <select value={leagueId ?? ""} onChange={(event) => setLeagueId(Number(event.target.value))} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option value="">Select league</option>{leagues.data.map((league) => <option key={league.id} value={league.id}>{league.name} · {league.seasonName}</option>)}</select> : null}</div>{!leagueId ? <Card className="mt-8 rounded-[22px] border-border/80 shadow-none"><CardContent className="grid place-items-center gap-3 p-12 text-center"><Flag className="size-9 text-primary" /><h2 className="text-xl font-bold">No league selected</h2><p className="text-sm text-muted-foreground">Create a league first to manage match results.</p></CardContent></Card> : <div className="mt-8 grid gap-8">{([ ["Awaiting confirmation", grouped.submitted], ["Disputed results", grouped.disputed], ["Confirmed results", grouped.confirmed], ["Scheduled matches", grouped.scheduled] ] as const).map(([title, rows]) => <section key={title}><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-bold">{title}</h2><p className="text-sm text-muted-foreground">{rows.length} match{rows.length === 1 ? "" : "es"}</p></div></div>{rows.length ? <div className="grid gap-3">{rows.map(renderCard)}</div> : <div className="rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">No {title.toLowerCase()}.</div>}</section>)}</div>}</div>;
}
