import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, UserRound } from "lucide-react";
import { useLocation, useRoute } from "wouter";

export default function TeamPage() {
  const [, params] = useRoute("/team/:teamId");
  const [, setLocation] = useLocation();
  const teamId = Number(params?.teamId) || 0;
  const query = trpc.player.team.useQuery({ teamId }, { enabled: teamId > 0, refetchOnWindowFocus: false });
  if (query.isLoading) return <div className="mx-auto max-w-[1100px] px-4 py-10 text-sm text-muted-foreground">Loading team page…</div>;
  if (query.error || !query.data) return <div className="mx-auto max-w-[700px] px-4 py-10"><Card className="rounded-[22px] shadow-none"><CardContent className="p-8"><p className="font-bold">This team page is unavailable.</p><p className="mt-2 text-sm text-muted-foreground">You need an approved registration or league ownership to view it.</p></CardContent></Card></div>;
  const { team, league, standing, players } = query.data;
  const stats = [["Played", standing?.played ?? 0], ["Wins", standing?.wins ?? 0], ["Draws", standing?.draws ?? 0], ["Losses", standing?.losses ?? 0], ["Goals For", standing?.goalsFor ?? 0], ["Goals Against", standing?.goalsAgainst ?? 0], ["Goal Difference", standing?.goalDifference ?? 0], ["Points", standing?.points ?? 0]];
  return <div className="mx-auto max-w-[1100px] px-4 py-6 sm:px-8 sm:py-10"><Button variant="ghost" onClick={() => setLocation("/player")} className="mb-5 -ml-3 rounded-xl"><ArrowLeft className="size-4" /> Back to player centre</Button><div className="rounded-[26px] bg-sidebar p-6 text-sidebar-foreground sm:p-9"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid size-20 place-items-center rounded-3xl bg-primary text-2xl font-black text-primary-foreground">{team.name.slice(0, 2).toUpperCase()}</div><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-primary">Team page · {league.name}</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{team.name}</h1><p className="mt-2 text-sm text-sidebar-foreground/65">{team.managerName} · {league.seasonName}</p></div></div></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_0.75fr]"><Card className="rounded-[22px] border-border/80 shadow-none"><CardHeader><CardTitle>Season record</CardTitle><CardDescription>Live values calculated from completed fixtures.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(([label, value]) => <div key={label} className="rounded-2xl bg-muted/60 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</CardContent></Card><Card className="rounded-[22px] border-border/80 shadow-none"><CardHeader><CardTitle>Registered players</CardTitle><CardDescription>{players.length} approved player{players.length === 1 ? "" : "s"} on this team.</CardDescription></CardHeader><CardContent className="grid gap-3">{players.length ? players.map(({ membership, user }) => <div key={membership.id} className="flex items-center gap-3 rounded-xl bg-muted/50 p-3"><div className="grid size-9 place-items-center rounded-full bg-primary/15 text-primary"><UserRound className="size-4" /></div><div><p className="font-semibold">{membership.playerName}</p><p className="text-xs text-muted-foreground">@{membership.username} · {user.email}</p></div></div>) : <p className="rounded-xl bg-muted/50 p-4 text-sm text-muted-foreground">No approved players yet.</p>}</CardContent></Card></div></div>;
}
